# Gradle Configuration
org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.workers.max=8
org.gradle.caching=true

# Project Properties
minecraft_version=1.21
loader_version=0.15.7
fabric_version=0.97.1+1.21

maven_group=com.parsmodernpvp
archives_base_name=parsmodernpvp
mod_version=21.0.0
